### ISSUE TITLE
setting exitHTMLparser_db not working anymore in 8.7

### ISSUE THREAD

**Issue by manuelLink** [FriendsOfTYPO3/rtehtmlarea#23]
the pagets-setting RTE.default.proc.exitHTMLparser_db seems to be nonfunctional in 8.7.1, i'm not sure if this is intentional or not.

**Comment by bmack** [comment]
Hey Manuel,

thank you for your report. Can you please post your PageTS configuration and your installed extensions here? Then I can try to reproduce this issue.

Thanks.
Benni.

**Comment by manuelLink** [comment]
Hi Benni,

Just tried it in a blank, new 8.7.24 installation, same results.

PageTS:
`RTE.default.proc {
  exitHTMLparser_db = 1
  exitHTMLparser_db {
    tags.b.remap = strong
    tags.i.remap = em
  }
}`

this code worked before, doesn't work in TYPO3 8.7 (tags are not replaced anymore)
Extensions are stock 8.7.24, just added rtehtmlarea in version 8.7.1

Thanks for taking a look at it,
Manuel

**Comment by bmack** [comment]
Hey Manuel,

I just checked this in my PageTS of an existing installation:

```
RTE.default.proc {
    exitHTMLparser_db = 1
    exitHTMLparser_db {
        tags.b.remap = benni
        tags.i.remap = em
    }
}
```

It basically remaps the "b" tag into a "benni" tag. And this is how it is stored in the database of my content element.

Now you also need to check if the problem is in your database, or if it's correct there, but the output in the frontend (which would be lib.parseFunc_RTE) also supports this tag and does not re-remap again.

If it's not stored properly in the database, please debug `typo3/sysext/core/Classes/Configuration/Richtext.php` (around line 67), this is where I started debugging - and where all the properties where done right.

**Comment by bmack** [comment]
@manuelLink any news here?

**Comment by liayn** [comment]
Closing due to lack of feedback.
