### ISSUE TITLE
<!DOCTYPE html Error

### ISSUE THREAD

**Issue by prdt3e** [FriendsOfTYPO3/rtehtmlarea#32]
Typo3: 8.7.20
rtehtmlarea: 8.7.2 @ohader 
Browser: Chrome (73.0.3683.86)

It is reported:
- no

IE11/Edge: works fine.

The Editor show in editor-area:
```php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html><head></head><body></body></html>
```

Thanks

**Comment by jpmschuler** [comment]
~~confirmed~~. This was a problem for rtehtmlarea:8.7.1 which was fixed with 8.7.2

Old comment:
Chrome 72.x works flawlessly, updating to 73.x breaks it (confirmed for WIN and OSX).
Can't find anything in the Chrome changelog which seems relevant, though.
![Bildschirmfoto 2019-03-26 um 13 17 44](https://user-images.githubusercontent.com/12411176/54996422-8c288f80-4fc9-11e9-9404-68dc93b30f71.png)

The iframe src looks quite odd:

```html
<iframe id="data_tt_content__23505__bodytext_-iframe" class="editorIframe" src="javascript: '&amp;lt;!DOCTYPE html
    PUBLIC &amp;quot;-//W3C//DTD XHTML 1.0 Transitional//EN&amp;quot;
    &amp;quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&amp;quot;&amp;gt;
&amp;lt;html&amp;gt;&amp;lt;head&amp;gt;&amp;lt;/head&amp;gt;&amp;lt;body&amp;gt;&amp;lt;/body&amp;gt;&amp;lt;/html&amp;gt;'" style="width: 564px; height: 327px;"></iframe> 
```

The `textAreaContainer` which shows the src is filled correctly with the bodytext.

**Comment by prdt3e** [comment]
Yes, that's exactly.

**Comment by robartde** [comment]
Chrome 73.0.3683.86 & T3 8.7.24 & htmlarea 8.7.2 work fine. Cleared Browser cache?

**Comment by bmack** [comment]
Hmm, good point. Maybe the JS file of RTEHtmlArea old version is cached in the browser...

**Comment by jpmschuler** [comment]
Indeed, that resolved the problem here. Sorry for the false confirmation. What a strange coincidence, didn't double check after seeing this issue, mea culpa.

**Comment by markenwirt** [comment]
Hey everyone,
we have a lot of customers with a TYPO3 7.6.X-Version and we tried to update the extension to 8.7.2 but it doesn't work. Do you have another fix for that? Maybe the codeline where we can change something and it works than? At the moment about 20 customers can't change anything in there TYPO3s.

**Comment by bmack** [comment]
@markenwirt you can't use the standalone extension which only suits TYPO3 v8 with TYPO3 v7. For TYPO3 v7 the ELTS program is recommended as there is a fix in place already.

Otherwise, you can see other tickets where this dicussion took place already:
https://github.com/FriendsOfTYPO3/rtehtmlarea/issues/26

For TYPO3 v8: Update the extension to rtehtmlarea 8.7.2 and clear browser caches
