### ISSUE TITLE
RTE not working again on typo3 V6 AND 7 since June 2021

### ISSUE THREAD

**Issue by wikafi** [FriendsOfTYPO3/rtehtmlarea#48]
Hello,
the problem with RTE in typo3 6 and 7 is present again.
on Chrome it's since the last version but it also bugs on firefox and Safari, edge, ...
it makes the sites unusable
![Snip20210615_2](https://user-images.githubusercontent.com/46966266/122066168-cbce3280-cdf2-11eb-999d-06c5af563042.png)
![Snip20210615_1](https://user-images.githubusercontent.com/46966266/122066172-ccff5f80-cdf2-11eb-93a1-261011c50fed.png)

**Comment by bnf** [comment]
See https://github.com/FriendsOfTYPO3/rtehtmlarea/issues/49 – I had the same problem and used the "older" Google Chrome "about:blank" fix and not yet the newer `''` iframe source, as fixed in https://github.com/FriendsOfTYPO3/rtehtmlarea/commit/a20e23445ca760ba94ed06dca05266b6e22a25fb

Are you sure you are using the most recent rtehtmlarea version 8.7.3, or are you still using 8.7.2?

**Comment by wikafi** [comment]
I'm talking about the versions of typo3 V6 (6.2.25) and V7 (7.6.32)
As far as I know, you can't use a 8XX version on a typo3 V6 or V7
moreover it concerns also the last version of chrome, that functioned at home also before the last update

**Comment by wikafi** [comment]
I have applied patch #49 and it works on version 7
I will test on version 6...
Thanks already...

**Comment by wikafi** [comment]
I can't find the files to modify in version 6
can you help me?
![Uploading Snip20210615_4.png…]()

**Comment by bnf** [comment]
> I have applied patch #49 and it works on version 7
> I will test on version 6...

No don't apply my (needlessly complex) patch from #49 (I only mentioned that because I used an older version like you did), please apply https://github.com/FriendsOfTYPO3/rtehtmlarea/commit/a20e23445ca760ba94ed06dca05266b6e22a25fb which is already part of the rtehtmlarea 8.7.3 release instead.

The changes can be applied to TYPO3 v7 in `typo3/sysext/rtehtmlarea/Resources/Public/JavaScript/HTMLArea/Editor/Editor.js` and for TYPO3 v6 in `typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js`.

Make sure to increase the `TYPO3_version` constant in `typo3/sysext/core/Classes/Core/SystemEnvironmentBuilder.php` in order for the cache busting parameter to be refreshed afterwards.

**Comment by wikafi** [comment]
Perfect, Thank you very much!
For those who are interested, the patch is at line 2187

for 6.2 it's /typo3/sysext/rtehtmlarea/htmlarea/htmlarea.js

Here is what needs to be changed 

//src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit ? about:blank;' : HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')

src: Ext.isGecko ? 'javascript:void(0);' : (Ext.isWebKit || Ext.isChrome ? '' : HTMLArea.editorUrl + 'Resources/Public/Html/blank.html')

**Comment by liayn** [comment]
A ready-made patch can be found here: https://reelworx.at/blog/detail/how-to-fix-rte-in-typo3-7-lts-for-chrome-73/

**Comment by melaniemedialight** [comment]
Hi !
I know that TYPO3 4.5 is very old but I have a site using this version.

Is there someone can help me to patch it, please ?
